# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FriendlyChat' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FriendlyChat
  
  	pod 'Firebase/Storage'
	pod 'Firebase/AdMob'
	pod 'Firebase/Auth'
	pod 'Firebase/Crash'
	pod 'Firebase/Database'
	pod 'Firebase/RemoteConfig'

end
